![image]([TPL_AUTHOR_AVATAR])[TPL_AUTHOR_NAME]([TPL_AUTHOR_EMAIL])](mailto:[TPL_AUTHOR_EMAIL]) 推送的

[TPL_REPO_FULL_NAME] 

提交备注: [TPL_COMMIT_MSG]

[ID：[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])

构建结果：[TPL_BUILD_STATUS]

[点击查看详情 [TPL_STATUS_EMOTICON)]]([TPL_BUILD_LINK])
